services:
  - type: web
    name: cocktail-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: cocktail-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cocktail-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: cocktail-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cocktail-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: cocktail-db
          property: database

databases:
  - name: cocktail-db
    databaseName: cocktails
    plan: free
    user: postgres
